dist: xenial
language: python
python:
  - "3.8"
  - "nightly"  # nightly build
# command to install dependencies
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - pip install flake8
install:
  - pip install
script: pytest # run tests
after_success:
  - codecov # submit coverage
