dist: xenial
python:
  - "3.8"
  - "nightly"  # nightly build
# command to install dependencies
before_install:
  - python -m pip install --upgrade pip
install:
  - pip install -r src/requirements.txt
# command to run tests
script: make test
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows